apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOY_NAME}-a
  labels:
    app: ${DEPLOY_NAME}-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${DEPLOY_NAME}-a
  template:
    metadata:
      labels:
        app: ${DEPLOY_NAME}-a
    spec:
      containers:
      - name: main
        image: ${DEPLOY_IMAGE}
        env:
        - name: APP_NAME
          value: "${DEPLOY_NAME}-a"
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOY_NAME}-b
  labels:
    app: ${DEPLOY_NAME}-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${DEPLOY_NAME}-b
  template:
    metadata:
      labels:
        app: ${DEPLOY_NAME}-b
    spec:
      containers:
      - name: main
        image: ${DEPLOY_IMAGE}
        env:
        - name: APP_NAME
          value: "${DEPLOY_NAME}-b"
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOY_NAME}-c
  labels:
    app: ${DEPLOY_NAME}-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${DEPLOY_NAME}-c
  template:
    metadata:
      labels:
        app: ${DEPLOY_NAME}-c
    spec:
      containers:
      - name: main
        image: ${DEPLOY_IMAGE}
        env:
        - name: APP_NAME
          value: "${DEPLOY_NAME}-c"
        ports:
        - containerPort: 5000
        imagePullPolicy: Always