apiVersion: v1
kind: Service
metadata:
  name: ${DEPLOY_NAME}-a
spec:
  selector:
    app: ${DEPLOY_NAME}-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ${DEPLOY_NAME}-b
spec:
  selector:
    app: ${DEPLOY_NAME}-b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ${DEPLOY_NAME}-c
spec:
  selector:
    app: ${DEPLOY_NAME}-c
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000